# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{data_miner}
  s.version = "0.2.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Seamus Abshere", "Andy Rossmeissl"]
  s.date = %q{2009-11-02}
  s.description = %q{Mine remote data into your ActiveRecord models. You can also perform associations and convert units.}
  s.email = %q{seamus@abshere.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "data_miner.gemspec",
     "lib/data_miner.rb",
     "lib/data_miner/active_record_ext.rb",
     "lib/data_miner/attribute.rb",
     "lib/data_miner/attribute_collection.rb",
     "lib/data_miner/configuration.rb",
     "lib/data_miner/dictionary.rb",
     "lib/data_miner/step.rb",
     "lib/data_miner/step/associate.rb",
     "lib/data_miner/step/await.rb",
     "lib/data_miner/step/callback.rb",
     "lib/data_miner/step/derive.rb",
     "lib/data_miner/step/import.rb",
     "lib/data_miner/william_james_cartesian_product.rb",
     "test/data_miner_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/seamusabshere/data_miner}
  s.rdoc_options = ["--charset=UTF-8", "--line-numbers", "--inline-source"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{dataminer}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Mine remote data into your ActiveRecord models.}
  s.test_files = [
    "test/data_miner_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<andand>, [">= 0"])
      s.add_runtime_dependency(%q<remote_table>, [">= 0"])
      s.add_runtime_dependency(%q<errata>, [">= 0"])
      s.add_runtime_dependency(%q<conversions>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<andand>, [">= 0"])
      s.add_dependency(%q<remote_table>, [">= 0"])
      s.add_dependency(%q<errata>, [">= 0"])
      s.add_dependency(%q<conversions>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<andand>, [">= 0"])
    s.add_dependency(%q<remote_table>, [">= 0"])
    s.add_dependency(%q<errata>, [">= 0"])
    s.add_dependency(%q<conversions>, [">= 0"])
  end
end

