# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{data_miner}
  s.version = "0.5.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Seamus Abshere", "Andy Rossmeissl", "Derek Kastner"]
  s.date = %q{2011-01-25}
  s.description = %q{Mine remote data into your ActiveRecord models. You can also perform associations and convert units.}
  s.email = %q{seamus@abshere.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "lib/data_miner.rb",
     "lib/data_miner/attribute.rb",
     "lib/data_miner/base.rb",
     "lib/data_miner/dictionary.rb",
     "lib/data_miner/import.rb",
     "lib/data_miner/process.rb",
     "lib/data_miner/run.rb",
     "lib/data_miner/schema.rb",
     "lib/data_miner/tap.rb",
     "lib/data_miner/verify.rb"
  ]
  s.homepage = %q{http://github.com/seamusabshere/data_miner}
  s.rdoc_options = ["--charset=UTF-8", "--line-numbers", "--inline-source"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Mine remote data into your ActiveRecord models.}
  s.test_files = [
    "test/data_miner/attribute_test.rb",
     "test/data_miner/verify_test.rb",
     "test/data_miner_test.rb",
     "test/support/aircraft.rb",
     "test/support/airport.rb",
     "test/support/automobile_fuel_type.rb",
     "test/support/automobile_variant.rb",
     "test/support/country.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<remote_table>, ["~> 1"])
      s.add_runtime_dependency(%q<escape>, [">= 0.0.4"])
      s.add_runtime_dependency(%q<activerecord>, [">= 2.3.4"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.4"])
      s.add_runtime_dependency(%q<andand>, [">= 1.3.1"])
      s.add_runtime_dependency(%q<conversions>, [">= 1.4.4"])
      s.add_runtime_dependency(%q<blockenspiel>, ["= 0.3.2"])
      s.add_runtime_dependency(%q<log4r>, [">= 1.1.7"])
      s.add_runtime_dependency(%q<errata>, [">= 0.2.1"])
      s.add_runtime_dependency(%q<taps>, [">= 0.3.11"])
      s.add_development_dependency(%q<loose_tight_dictionary>, [">= 0.0.5"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<mysql>, [">= 0"])
    else
      s.add_dependency(%q<remote_table>, ["~> 1"])
      s.add_dependency(%q<escape>, [">= 0.0.4"])
      s.add_dependency(%q<activerecord>, [">= 2.3.4"])
      s.add_dependency(%q<activesupport>, [">= 2.3.4"])
      s.add_dependency(%q<andand>, [">= 1.3.1"])
      s.add_dependency(%q<conversions>, [">= 1.4.4"])
      s.add_dependency(%q<blockenspiel>, ["= 0.3.2"])
      s.add_dependency(%q<log4r>, [">= 1.1.7"])
      s.add_dependency(%q<errata>, [">= 0.2.1"])
      s.add_dependency(%q<taps>, [">= 0.3.11"])
      s.add_dependency(%q<loose_tight_dictionary>, [">= 0.0.5"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<mysql>, [">= 0"])
    end
  else
    s.add_dependency(%q<remote_table>, ["~> 1"])
    s.add_dependency(%q<escape>, [">= 0.0.4"])
    s.add_dependency(%q<activerecord>, [">= 2.3.4"])
    s.add_dependency(%q<activesupport>, [">= 2.3.4"])
    s.add_dependency(%q<andand>, [">= 1.3.1"])
    s.add_dependency(%q<conversions>, [">= 1.4.4"])
    s.add_dependency(%q<blockenspiel>, ["= 0.3.2"])
    s.add_dependency(%q<log4r>, [">= 1.1.7"])
    s.add_dependency(%q<errata>, [">= 0.2.1"])
    s.add_dependency(%q<taps>, [">= 0.3.11"])
    s.add_dependency(%q<loose_tight_dictionary>, [">= 0.0.5"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<mysql>, [">= 0"])
  end
end

